### PR TITLE
Compatibility with SQ 6.1

### LINKED ISSUE #4: Fix compatibility with SQ 6.1+
Plugin is using deprecated APIs that will be removed in SonarQube 6.x like org.sonar.api.scan.filesystem.ModuleFileSystem
https://jira.sonarsource.com/browse/SONAR-7864

### PR DESCRIPTION
**Pull request by bguerin**
Fix #4

### CODE REVIEW

**Comment by agaidaichuk** [comment]
Hi, Benoit.
First of all, thanks a lot for so quick fix.
But is there any ETA to get it merged?

**Comment by agaidaichuk** [comment]
Hi, Benoit.
First of all, thanks a lot for so quick fix.
But is there any ETA to get it merged?

**Comment by bguerin** [comment]
I am not the maintener of this plugin ... so cannot answer :(

**Comment by ejocharcole** [comment]
This fix works very well, I'm using it with my Sonar install. thank you!  (I had an unusable Sonar 6.1  until I saw this PR)

**Comment by arandre** [comment]
Hi @ejocharcole and @bguerin 

Thanks for getting this to work - just like @ejocharcole, Sonar 6.1 was dead in the water for me.  Question - how did you install it for Sonar?  Sorry for the question, but this is all new to me.

Thanks

**Comment by ejocharcole** [comment]
Checkout the branch and maven package.
stop sonar
 then just copy the jar into extensions/plugins in your Sonar install - and remove the old version
start sonar

then just check the plugins page in the console, you should see your new version of the plugin

if you've not updated your other plugins for a while you might find you need to update them - e.g. the Java plugin. I usually just download them and install them all myself in extensions/plugins
(the Sonar console does have a feature for updating some plugins directly, but it didn't seem to work last time I tried it)

**Comment by arandre** [comment]
@ejocharcole - I checked out the branch but don't see the maven package.

**Comment by ejocharcole** [comment]
are you familiar with Maven? you need to run mvn package 
(i.e. in your IDE or command line)

**Comment by arandre** [comment]
yes - I got it right after i submitted the comment.  Thanks once again!

**Comment by ervinadr** [comment]
Hi, 
We faced this problem as well.
What is a plan when this is going to be merged?
Thanks

**Comment by benzonico** [comment]
To answer the questions about ETA on merging this PR please carefully read the following :  https://github.com/SonarQubeCommunity/sonar-cobertura#plugin-seeking-maintainers

This plugin is no longer maintained by Sonarsource, as a consequence in order for this PR to be merged someone as to step up from community to become maintainer.

**Comment by ejocharcole** [comment]
thanks for the 6.2 fix @bguerin , works great.

**Pull request merged**
